#!/bin/sh
BAUDRATE=`uci get yunbridge.config.baudrate`
[ -n "${BAUDRATE}" ] || BAUDRATE=250000

#[ -e /lib/ramips.sh -a ${BAUDRATE} = 250000 ] && BAUDRATE=2500000

stty -F /dev/ttyS0 ${BAUDRATE} clocal cread cs8 -cstopb -parenb
exec < /dev/ttyS0
exec > /dev/ttyS0
exec 2> /dev/ttyS0
askfirst bin/ash --login
